# Generated by Django 2.2.20 on 2021-06-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210625_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='m_pwd',
        ),
    ]
